subroutine sfincs_finalize()

  use globalVariables
  use xGrid
  use indices
  use export_f

  implicit none

  !globalVariables array
  if(allocated(Nxi_for_x)) deallocate( Nxi_for_x, min_x_for_L)
  if(allocated(theta)) deallocate( theta, zeta, x, x_plus1)
  if(allocated(thetaWeights)) deallocate( thetaWeights, zetaWeights)
  if(allocated(ddtheta)) deallocate( ddtheta, ddzeta)
  if(allocated(ddtheta_ExB_plus)) deallocate( ddtheta_ExB_plus, ddtheta_ExB_minus)
  if(allocated(ddzeta_ExB_plus)) deallocate( ddzeta_ExB_plus, ddzeta_ExB_minus)
  if(allocated(ddtheta_magneticDrift_plus)) deallocate( ddtheta_magneticDrift_plus, ddtheta_magneticDrift_minus)
  if(allocated(ddzeta_magneticDrift_plus)) deallocate( ddzeta_magneticDrift_plus, ddzeta_magneticDrift_minus)
  if(allocated(xWeights)) deallocate( xWeights, xPotentials)
  if(allocated(x2)) deallocate( x2, expx2)
  if(allocated(ddx)) deallocate( ddx, d2dx2, ddxPotentials, d2dx2Potentials)
  if(allocated(ddx_xDot_plus)) deallocate( ddx_xDot_plus, ddx_xDot_preconditioner_plus)
  if(allocated(ddx_xDot_minus)) deallocate( ddx_xDot_minus, ddx_xDot_preconditioner_minus)
  if(allocated(ddx_preconditioner)) deallocate( ddx_preconditioner)
  if(allocated(ddtheta_preconditioner)) deallocate( ddtheta_preconditioner)
  if(allocated(ddzeta_preconditioner)) deallocate( ddzeta_preconditioner)
  if(allocated(interpolateXToXPotentials)) deallocate( interpolateXToXPotentials)
  if(allocated(RosenbluthPotentialTerms)) deallocate( RosenbluthPotentialTerms)
  if(allocated(BHat)) deallocate( BHat, dBHatdtheta, dBHatdzeta, dBHatdpsiHat, DHat)
  if(allocated(BHat_sub_psi)) deallocate( BHat_sub_psi, dBHat_sub_psi_dtheta, dBHat_sub_psi_dzeta)
  if(allocated(BHat_sub_theta)) deallocate( BHat_sub_theta, dBHat_sub_theta_dzeta, dBHat_sub_theta_dpsiHat)
  if(allocated(BHat_sub_zeta)) deallocate( BHat_sub_zeta, dBHat_sub_zeta_dtheta, dBHat_sub_zeta_dpsiHat)
  if(allocated(BHat_sup_theta)) deallocate( BHat_sup_theta, dBHat_sup_theta_dzeta, dBHat_sup_theta_dpsiHat)
  if(allocated(BHat_sup_zeta)) deallocate( BHat_sup_zeta, dBHat_sup_zeta_dtheta, dBHat_sup_zeta_dpsiHat)
  if(allocated(BDotCurlB)) deallocate( BDotCurlB, uHat, gradpsidotgradB_overgpsipsi, gpsipsi)
  if(allocated(sources)) deallocate( sources, jHat, Phi1Hat, dPhi1Hatdtheta, dPhi1Hatdzeta)
  if(allocated(densityPerturbation)) deallocate( densityPerturbation, totalDensity)
  if(allocated(pressurePerturbation)) deallocate( pressurePerturbation, totalPressure, pressureAnisotropy)
  if(allocated(flow)) deallocate( flow, velocityUsingFSADensity, velocityUsingTotalDensity)
  if(allocated(MachUsingFSAThermalSpeed)) deallocate( MachUsingFSAThermalSpeed)
  if(allocated(particleFluxBeforeSurfaceIntegral_vm0)) deallocate( particleFluxBeforeSurfaceIntegral_vm0)
  if(allocated(particleFluxBeforeSurfaceIntegral_vm)) deallocate( particleFluxBeforeSurfaceIntegral_vm)
  if(allocated(particleFluxBeforeSurfaceIntegral_vE0)) deallocate( particleFluxBeforeSurfaceIntegral_vE0)
  if(allocated(particleFluxBeforeSurfaceIntegral_vE)) deallocate( particleFluxBeforeSurfaceIntegral_vE)
  if(allocated(momentumFluxBeforeSurfaceIntegral_vm0)) deallocate( momentumFluxBeforeSurfaceIntegral_vm0)
  if(allocated(momentumFluxBeforeSurfaceIntegral_vm)) deallocate( momentumFluxBeforeSurfaceIntegral_vm)
  if(allocated(momentumFluxBeforeSurfaceIntegral_vE0)) deallocate( momentumFluxBeforeSurfaceIntegral_vE0)
  if(allocated(momentumFluxBeforeSurfaceIntegral_vE)) deallocate( momentumFluxBeforeSurfaceIntegral_vE)
  if(allocated(heatFluxBeforeSurfaceIntegral_vm0)) deallocate( heatFluxBeforeSurfaceIntegral_vm0)
  if(allocated(heatFluxBeforeSurfaceIntegral_vm)) deallocate( heatFluxBeforeSurfaceIntegral_vm)
  if(allocated(heatFluxBeforeSurfaceIntegral_vE0)) deallocate( heatFluxBeforeSurfaceIntegral_vE0)
  if(allocated(heatFluxBeforeSurfaceIntegral_vE)) deallocate( heatFluxBeforeSurfaceIntegral_vE)
  if(allocated(NTVBeforeSurfaceIntegral)) deallocate( NTVBeforeSurfaceIntegral)
  if(allocated(NTVKernel)) deallocate( NTVKernel)
  if(allocated(FSADensityPerturbation)) deallocate( FSADensityPerturbation, FSAPressurePerturbation)
  if(allocated(FSABFlow)) deallocate( FSABFlow, FSABVelocityUsingFSADensity)
  if(allocated(FSABVelocityUsingFSADensityOverB0)) deallocate( FSABVelocityUsingFSADensityOverB0)
  if(allocated(FSABVelocityUsingFSADensityOverRootFSAB2)) deallocate( FSABVelocityUsingFSADensityOverRootFSAB2)
  if(allocated(particleFlux_vm0_psiHat)) deallocate( particleFlux_vm0_psiHat)
  if(allocated(particleFlux_vm0_psiN)) deallocate( particleFlux_vm0_psiN)
  if(allocated(particleFlux_vm0_rHat)) deallocate( particleFlux_vm0_rHat)
  if(allocated(particleFlux_vm0_rN)) deallocate( particleFlux_vm0_rN)
  if(allocated(particleFlux_vm_psiHat)) deallocate( particleFlux_vm_psiHat)
  if(allocated(particleFlux_vm_psiN)) deallocate( particleFlux_vm_psiN)
  if(allocated(particleFlux_vm_rHat)) deallocate( particleFlux_vm_rHat)
  if(allocated(particleFlux_vm_rN)) deallocate( particleFlux_vm_rN)
  if(allocated(particleFlux_vE0_psiHat)) deallocate( particleFlux_vE0_psiHat)
  if(allocated(particleFlux_vE0_psiN)) deallocate( particleFlux_vE0_psiN)
  if(allocated(particleFlux_vE0_rHat)) deallocate( particleFlux_vE0_rHat)
  if(allocated(particleFlux_vE0_rN)) deallocate( particleFlux_vE0_rN)
  if(allocated(particleFlux_vE_psiHat)) deallocate( particleFlux_vE_psiHat)
  if(allocated(particleFlux_vE_psiN)) deallocate( particleFlux_vE_psiN)
  if(allocated(particleFlux_vE_rHat)) deallocate( particleFlux_vE_rHat)
  if(allocated(particleFlux_vE_rN)) deallocate( particleFlux_vE_rN)
  if(allocated(particleFlux_vd1_psiHat)) deallocate( particleFlux_vd1_psiHat)
  if(allocated(particleFlux_vd1_psiN)) deallocate( particleFlux_vd1_psiN)
  if(allocated(particleFlux_vd1_rHat)) deallocate( particleFlux_vd1_rHat)
  if(allocated(particleFlux_vd1_rN)) deallocate( particleFlux_vd1_rN)
  if(allocated(particleFlux_vd_psiHat)) deallocate( particleFlux_vd_psiHat)
  if(allocated(particleFlux_vd_psiN)) deallocate( particleFlux_vd_psiN)
  if(allocated(particleFlux_vd_rHat)) deallocate( particleFlux_vd_rHat)
  if(allocated(particleFlux_vd_rN)) deallocate( particleFlux_vd_rN)
  if(allocated(classicalParticleFlux_psiHat)) deallocate( classicalParticleFlux_psiHat)
  if(allocated(classicalParticleFlux_psiN)) deallocate( classicalParticleFlux_psiN)
  if(allocated(classicalParticleFlux_rHat)) deallocate( classicalParticleFlux_rHat)
  if(allocated(classicalParticleFlux_rN)) deallocate( classicalParticleFlux_rN)
  if(allocated(classicalParticleFluxNoPhi1_psiHat)) deallocate( classicalParticleFluxNoPhi1_psiHat)
  if(allocated(classicalParticleFluxNoPhi1_psiN)) deallocate( classicalParticleFluxNoPhi1_psiN)
  if(allocated(classicalParticleFluxNoPhi1_rHat)) deallocate( classicalParticleFluxNoPhi1_rHat)
  if(allocated(classicalParticleFluxNoPhi1_rN)) deallocate( classicalParticleFluxNoPhi1_rN)
  if(allocated(classicalHeatFlux_psiHat)) deallocate( classicalHeatFlux_psiHat)
  if(allocated(classicalHeatFlux_psiN)) deallocate( classicalHeatFlux_psiN)
  if(allocated(classicalHeatFlux_rHat)) deallocate( classicalHeatFlux_rHat)
  if(allocated(classicalHeatFlux_rN)) deallocate( classicalHeatFlux_rN)
  if(allocated(classicalHeatFluxNoPhi1_psiHat)) deallocate( classicalHeatFluxNoPhi1_psiHat)
  if(allocated(classicalHeatFluxNoPhi1_psiN)) deallocate( classicalHeatFluxNoPhi1_psiN)
  if(allocated(classicalHeatFluxNoPhi1_rHat)) deallocate( classicalHeatFluxNoPhi1_rHat)
  if(allocated(classicalHeatFluxNoPhi1_rN)) deallocate( classicalHeatFluxNoPhi1_rN)
  if(allocated(momentumFlux_vm0_psiHat)) deallocate( momentumFlux_vm0_psiHat)
  if(allocated(momentumFlux_vm0_psiN)) deallocate( momentumFlux_vm0_psiN)
  if(allocated(momentumFlux_vm0_rHat)) deallocate( momentumFlux_vm0_rHat)
  if(allocated(momentumFlux_vm0_rN)) deallocate( momentumFlux_vm0_rN)
  if(allocated(momentumFlux_vm_psiHat)) deallocate( momentumFlux_vm_psiHat)
  if(allocated(momentumFlux_vm_psiN)) deallocate( momentumFlux_vm_psiN)
  if(allocated(momentumFlux_vm_rHat)) deallocate( momentumFlux_vm_rHat)
  if(allocated(momentumFlux_vm_rN)) deallocate( momentumFlux_vm_rN)
  if(allocated(momentumFlux_vE0_psiHat)) deallocate( momentumFlux_vE0_psiHat)
  if(allocated(momentumFlux_vE0_psiN)) deallocate( momentumFlux_vE0_psiN)
  if(allocated(momentumFlux_vE0_rHat)) deallocate( momentumFlux_vE0_rHat)
  if(allocated(momentumFlux_vE0_rN)) deallocate( momentumFlux_vE0_rN)
  if(allocated(momentumFlux_vE_psiHat)) deallocate( momentumFlux_vE_psiHat)
  if(allocated(momentumFlux_vE_psiN)) deallocate( momentumFlux_vE_psiN)
  if(allocated(momentumFlux_vE_rHat)) deallocate( momentumFlux_vE_rHat)
  if(allocated(momentumFlux_vE_rN)) deallocate( momentumFlux_vE_rN)
  if(allocated(momentumFlux_vd1_psiHat)) deallocate( momentumFlux_vd1_psiHat)
  if(allocated(momentumFlux_vd1_psiN)) deallocate( momentumFlux_vd1_psiN)
  if(allocated(momentumFlux_vd1_rHat)) deallocate( momentumFlux_vd1_rHat)
  if(allocated(momentumFlux_vd1_rN)) deallocate( momentumFlux_vd1_rN)
  if(allocated(momentumFlux_vd_psiHat)) deallocate( momentumFlux_vd_psiHat)
  if(allocated(momentumFlux_vd_psiN)) deallocate( momentumFlux_vd_psiN)
  if(allocated(momentumFlux_vd_rHat)) deallocate( momentumFlux_vd_rHat)
  if(allocated(momentumFlux_vd_rN)) deallocate( momentumFlux_vd_rN)
  if(allocated(heatFlux_vm0_psiHat)) deallocate( heatFlux_vm0_psiHat)
  if(allocated(heatFlux_vm0_psiN)) deallocate( heatFlux_vm0_psiN)
  if(allocated(heatFlux_vm0_rHat)) deallocate( heatFlux_vm0_rHat)
  if(allocated(heatFlux_vm0_rN)) deallocate( heatFlux_vm0_rN)
  if(allocated(heatFlux_vm_psiHat)) deallocate( heatFlux_vm_psiHat)
  if(allocated(heatFlux_vm_psiN)) deallocate( heatFlux_vm_psiN)
  if(allocated(heatFlux_vm_rHat)) deallocate( heatFlux_vm_rHat)
  if(allocated(heatFlux_vm_rN)) deallocate( heatFlux_vm_rN)
  if(allocated(heatFlux_vE0_psiHat)) deallocate( heatFlux_vE0_psiHat)
  if(allocated(heatFlux_vE0_rHat)) deallocate( heatFlux_vE0_rHat)
  if(allocated(heatFlux_vE0_rN)) deallocate( heatFlux_vE0_rN)
  if(allocated(heatFlux_vE0_psiN)) deallocate( heatFlux_vE0_psiN)
  if(allocated(heatFlux_vE_psiHat)) deallocate( heatFlux_vE_psiHat)
  if(allocated(heatFlux_vE_rHat)) deallocate( heatFlux_vE_rHat)
  if(allocated(heatFlux_vE_rN)) deallocate( heatFlux_vE_rN)
  if(allocated(heatFlux_vE_psiN)) deallocate( heatFlux_vE_psiN)
  if(allocated(heatFlux_vd1_psiHat)) deallocate( heatFlux_vd1_psiHat)
  if(allocated(heatFlux_vd1_psiN)) deallocate( heatFlux_vd1_psiN)
  if(allocated(heatFlux_vd1_rHat)) deallocate( heatFlux_vd1_rHat)
  if(allocated(heatFlux_vd1_rN)) deallocate( heatFlux_vd1_rN)
  if(allocated(heatFlux_vd_psiHat)) deallocate( heatFlux_vd_psiHat)
  if(allocated(heatFlux_vd_psiN)) deallocate( heatFlux_vd_psiN)
  if(allocated(heatFlux_vd_rHat)) deallocate( heatFlux_vd_rHat)
  if(allocated(heatFlux_vd_rN)) deallocate( heatFlux_vd_rN)
  if(allocated(heatFlux_withoutPhi1_psiHat)) deallocate( heatFlux_withoutPhi1_psiHat)
  if(allocated(heatFlux_withoutPhi1_psiN)) deallocate( heatFlux_withoutPhi1_psiN)
  if(allocated(heatFlux_withoutPhi1_rHat)) deallocate( heatFlux_withoutPhi1_rHat)
  if(allocated(heatFlux_withoutPhi1_rN)) deallocate( heatFlux_withoutPhi1_rN)
  if(allocated(particleFlux_vm_psiHat_vs_x)) deallocate( particleFlux_vm_psiHat_vs_x)
  if(allocated(heatFlux_vm_psiHat_vs_x)) deallocate( heatFlux_vm_psiHat_vs_x)
  if(allocated(FSABFlow_vs_x)) deallocate( FSABFlow_vs_x)
  if(allocated(NTV)) deallocate( NTV)
  if(allocated(transportMatrix)) deallocate( transportMatrix)
  if(allocated(bcdata)) deallocate(bcdata)

  if(allocated(map_theta_to_export_f_theta))deallocate(map_theta_to_export_f_theta)
  if(allocated(map_zeta_to_export_f_zeta))deallocate(map_zeta_to_export_f_zeta)
  if(allocated(map_x_to_export_f_x))deallocate(map_x_to_export_f_x)
  if(allocated(map_xi_to_export_f_xi))deallocate(map_xi_to_export_f_xi)
  if(allocated(delta_f))deallocate(delta_f)
  if(allocated(full_f))deallocate(full_f)

  if(allocated(externalRosenPotentialTerms))deallocate(externalRosenPotentialTerms)
  if(allocated(externalN))deallocate(externalN)
  if(allocated(externalCharges))deallocate(externalCharges)
  if(allocated(FSABExternalFlow)) deallocate(FSABExternalFlow)
  if(allocated(externalFlow)) deallocate(externalFlow)
  
  
  call xGrid_finalize()
  call indices_finalize()

end subroutine sfincs_finalize

