#!/usr/bin/env python

# This script will not work if called directly.
# From the command line, you should call sfincsScan instead.

profilesFilename = 'profiles'

import os, inspect

print "This is "+ inspect.getfile(inspect.currentframe())
print "Beginning a scan of Er inside a scan over radius."

# Determine radii to use, and n & T at those radii:
skipExistingDirectories = False
execfile(os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))+"/radialScans")

while True:
    proceed=raw_input("Should I go ahead and launch Er scans at these "+str(len(radii))+" radii? [y/n] ")
    if proceed=="y" or proceed=="n":
        break
    print "You must enter either y or n."

if proceed=="n":
    exit(0)
print "launching jobs..."

# Read in the job.sfincsScan file:
with open(jobFilename, 'r') as f:
    jobFile = f.readlines()

for runNum in range(len(radii)):
    directory = directories[runNum]
    print "Beginning to handle radius "+str(runNum+1)+" of "+str(len(radii))+": "+directory

    # To be extra safe, check again to see if the directory exists.
    if os.path.exists(directory):
        print "Directory "+directory+" already exists."
    else:
        print "Creating directory "+directory
        os.makedirs(directory)
    os.chdir(directory)

    # Copy the job.sfincsScan file:
    thisJobFile = list(jobFile)
    ## This next function is defined separately for each system in sfincsScan
    #nameJobFile(thisJobFile,directory)
    f = open(jobFilename,"w")
    f.writelines(thisJobFile)
    f.close()

    # Now copy the input.namelist file:


    ##The following section rewritten by AM 2015-12##
    #################################################

    f = open(filename,"w")
    for line in inputFile:
        # Set sfincsScan directives:
        if namelistLineContainsSS(line,"scanType"):
##            line = "!ss scanType = 2  ! set by sfincsScan_5.\n" ##Commented by AM
            continue ##Added by AM
        if namelistLineContainsSS(line,"NErs"):
##            line = "!ss NErs = "+str(int(NErs[runNum]))+"  ! set by sfincsScan_5.\n" ##Commented by AM
            continue ##Added by AM
        if namelistLineContainsSS(line,"dPhiHatd"+radiusNameForGradients+"Max"):
##            line = "!ss dPhiHatd"+radiusNameForGradients+"Max = "+str(dPhiHatdradius_max[runNum])+"  ! set by sfincsScan_5.\n" ##Commented by AM
            continue ##Added by AM
        if namelistLineContainsSS(line,"dPhiHatd"+radiusNameForGradients+"Min"):
##            line = "!ss dPhiHatd"+radiusNameForGradients+"Min = "+str(dPhiHatdradius_min[runNum])+"  ! set by sfincsScan_5.\n" ##Commented by AM
            continue ##Added by AM
        # Now set fortran variables:
        if namelistLineContains(line,radiusName+"_wish"):
##            line = "  "+radiusName+"_wish = "+str(radii[runNum])+" ! Set by sfincsScan_5.\n" ##Commented by AM
            continue ##Added by AM
        if namelistLineContains(line,"nHats"):
##            line = "  nHats =" ##Commented by AM
##            for ispecies in range(Nspecies): ##Commented by AM
##                line += " "+str(nHats[ispecies][runNum]) ##Commented by AM
##            line += " ! Set by sfincsScan_5.\n" ##Commented by AM
            continue ##Added by AM
        if namelistLineContains(line,"dnHatd"+radiusNameForGradients+"s"):
##            line = "  dnHatd"+radiusNameForGradients+"s =" ##Commented by AM
##            for ispecies in range(Nspecies): ##Commented by AM
##                line += " "+str(dnHatdradii[ispecies][runNum]) ##Commented by AM
##            line += " ! Set by sfincsScan_5.\n" ##Commented by AM
            continue ##Added by AM
        if namelistLineContains(line,"THats"):
##            line = "  THats =" ##Commented by AM 
##            for ispecies in range(Nspecies): ##Commented by AM
##                line += " "+str(THats[ispecies][runNum]) ##Commented by AM 
##            line += " ! Set by sfincsScan_5.\n" ##Commented by AM
            continue ##Added by AM
        if namelistLineContains(line,"dTHatd"+radiusNameForGradients+"s"):
##            line = "  dTHatd"+radiusNameForGradients+"s =" ##Commented by AM
##            for ispecies in range(Nspecies): ##Commented by AM
##                line += " "+str(dTHatdradii[ispecies][runNum]) ##Commented by AM
##            line += " ! Set by sfincsScan_5.\n" ##Commented by AM
            continue ##Added by AM

        ##Added by AM 2015-12##
        if line.strip().find("&geometryParameters") == 0 :
            line += "  "+radiusName+"_wish = "+str(radii[runNum])+" ! Set by sfincsScan_5.\n"

        if line.strip().find("&speciesParameters") == 0 :
            line += "  nHats =" 
            for ispecies in range(Nspecies):
                line += " "+str(nHats[ispecies][runNum])
            line += " ! Set by sfincsScan_5.\n"    

            line += "  dnHatd"+radiusNameForGradients+"s ="
            for ispecies in range(Nspecies):
                line += " "+str(dnHatdradii[ispecies][runNum])
            line += " ! Set by sfincsScan_5.\n"

            line += "  THats ="
            for ispecies in range(Nspecies):
                line += " "+str(THats[ispecies][runNum])
            line += " ! Set by sfincsScan_5.\n"

            line += "  dTHatd"+radiusNameForGradients+"s ="
            for ispecies in range(Nspecies):
                line += " "+str(dTHatdradii[ispecies][runNum])
            line += " ! Set by sfincsScan_5.\n"    

        #######################    
        f.write(line)

    ##Added by AM 2015-12, Write sfincsScan options##
    line = "!ss scanType = 2  ! set by sfincsScan_5.\n"
    line += "!ss NErs = "+str(int(NErs[runNum]))+"  ! set by sfincsScan_5.\n"
    line += "!ss dPhiHatd"+radiusNameForGradients+"Max = "+str(dPhiHatdradius_max[runNum])+"  ! set by sfincsScan_5.\n"
    line += "!ss dPhiHatd"+radiusNameForGradients+"Min = "+str(dPhiHatdradius_min[runNum])+"  ! set by sfincsScan_5.\n"
    f.write(line)

    f.close()

    #################################################

    # Submit the Er scan:
    ##Modified by AM 2015-12-09##
##    submitCommand = "sfincsScan -f" ##Commented by AM 2015-12
    submitCommand = os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))+"/sfincsScan -f" ##Added by AM 2015-12
    #############################
    try:
        # We need to include .split(" ") to separate the command-line arguments into an array of strings.   
        # I'm not sure why python requires this. 
        submissionResult = subprocess.call(submitCommand.split(" "))
        #submissionResult=0
    except:
        print "ERROR! Unable to submit run "+directory+" for some reason."
        raise
    else:
        if submissionResult==0:
            print "No errors submitting job "+directory
        else:
            print "Nonzero exit code returned when trying to submit job "+directory

    os.chdir("..")


