#!/usr/bin/env python

# This script will not work if called directly.
# From the command line, you should call sfincsScan instead.

import os, inspect

print "This is "+ inspect.getfile(inspect.currentframe())
print "Beginning a scan of nu_n."

nu_n = readVariable("nu_n","float")
N_nu_n = readScanVariable("N_nu_n","int")
nu_n_min_factor = readScanVariable("nu_n_min_factor","float")
nu_n_max_factor = readScanVariable("nu_n_max_factor","float")

nu_ns = logspace(nu_n*nu_n_max_factor, nu_n*nu_n_min_factor, N_nu_n)

print "Here are the values of nu_n we will use for this scan:"
print nu_ns

directories = ["nu_n_"+str(this_nu_n) for this_nu_n in nu_ns]

nu_ns_copy = list(nu_ns)
directories_copy = list(directories)

# See if any runs with the same description already exist.
# This happens if you re-run sfincsScan more than once in the same directory.
for i in range(len(nu_ns_copy)):
    directory = directories_copy[i]
    if os.path.exists(directory):
        print "Warning: directory "+directory+" already exists, so skipping this run."
        nu_ns.remove(nu_ns_copy[i])
        directories.remove(directory)

print
print "Here are the directories that will be created:"
print directories

while True:
    proceed=raw_input("Should I go ahead and launch these "+str(len(nu_ns))+" jobs? [y/n] ")
    if proceed=="y" or proceed=="n":
        break
    print "You must enter either y or n."

if proceed=="n":
    exit(0)
print "launching jobs..."

# Read in the job.sfincsScan file:
with open(jobFilename, 'r') as f:
    jobFile = f.readlines()

for runNum in range(len(nu_ns)):
    directory = directories[runNum]
    print "Beginning to handle job "+str(runNum+1)+" of "+str(len(nu_ns))+": "+directory

    # To be extra safe, check again to see if the directory exists.
    if os.path.exists(directory):
        print "Warning: directory "+directory+" already exists."
        i = -1
        while True:
            i += 1
            directory2 = directory+"_"+str(i)
            if not os.path.exists(directory2):
                break
        directory = directory2
    os.makedirs(directory)
    os.chdir(directory)

    # Copy the job.sfincsScan file:
    thisJobFile = list(jobFile)
    # This next function is defined separately for each system in sfincsScan
    nameJobFile(thisJobFile,directory)
    f = open(jobFilename,"w")
    f.writelines(thisJobFile)
    f.close()

    # Now copy the input.namelist file:
    f = open(filename,"w")
    for line in inputFile:
        if namelistLineContains(line,"nu_n"):
            line = "  nu_n = "+str(nu_ns[runNum])+" ! Set by sfincsScan.\n"
        f.write(line)
    f.close()

    # Submit the sfincs job:
    try:
        # We need to include .split(" ") to separate the command-line arguments into an array of strings.   
        # I'm not sure why python requires this. 
        submissionResult = subprocess.call(submitCommand.split(" "))
        #submissionResult=0
    except:
        print "ERROR! Unable to submit run "+directory+" for some reason."
        raise
    else:
        if submissionResult==0:
            print "No errors submitting job "+directory
        else:
            print "Nonzero exit code returned when trying to submit job "+directory

    os.chdir("..")
