# These next 2 includes set FC, FLINKER, and PETSC_LIB:
include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules

# Any other flags for compiling, such as -I include flags:
EXTRA_COMPILE_FLAGS =

# Any other flags for linking, such as -l library flags:
EXTRA_LINK_FLAGS =

