TARGET = Adjoint\ SFINCS\ Implementation\ Notes

.PHONY: all

all: 
	pdflatex $(TARGET)

clean:
	rm $(TARGET).aux
	rm $(TARGET).pdf
	rm $(TARGET).bbl
	rm $(TARGET).blg
	rm $(TARGET).log
	rm $(TARGET).synctex.gz
